#pragma once
#include "clp.h"
enum { clp_val_suffixdouble = Clp_ValFirstUser };
enum {
    opt_nolog = 1,
    opt_pin,
    opt_logdir,
    opt_port,
    opt_ckpdir,
    opt_duration,
    opt_test,
    opt_test_name,
    opt_threads,
    opt_cores,
    opt_print,
    opt_norun,
    opt_checkpoint,
    opt_limit,
    opt_epoch_interval,
    opt_slave,
    opt_slave_instr
};
static const Clp_Option options[] = {
    {"slave", 0, opt_slave, 0, 0},
    {"slave-instr", 0, opt_slave_instr, Clp_ValString, 0},
    {"no-log", 0, opt_nolog, 0, 0},
    {0, 'n', opt_nolog, 0, 0},
    {"no-run", 0, opt_norun, 0, 0},
    {"pin", 'p', opt_pin, 0, Clp_Negate},
    {"logdir", 0, opt_logdir, Clp_ValString, 0},
    {"ld", 0, opt_logdir, Clp_ValString, 0},
    {"checkpoint", 'c', opt_checkpoint, Clp_ValDouble,
     Clp_Optional | Clp_Negate},
    {"ckp", 0, opt_checkpoint, Clp_ValDouble, Clp_Optional | Clp_Negate},
    {"ckpdir", 0, opt_ckpdir, Clp_ValString, 0},
    {"ckdir", 0, opt_ckpdir, Clp_ValString, 0},
    {"cd", 0, opt_ckpdir, Clp_ValString, 0},
    {"port", 0, opt_port, Clp_ValInt, 0},
    {"duration", 'd', opt_duration, Clp_ValDouble, 0},
    {"limit", 'l', opt_limit, clp_val_suffixdouble, 0},
    {"test", 0, opt_test, Clp_ValString, 0},
    {"test-rw1", 0, opt_test_name, 0, 0},
    {"test-rw2", 0, opt_test_name, 0, 0},
    {"test-rw3", 0, opt_test_name, 0, 0},
    {"test-rw4", 0, opt_test_name, 0, 0},
    {"test-rw5", 0, opt_test_name, 0, 0},
    {"test-rw16", 0, opt_test_name, 0, 0},
    {"test-palm", 0, opt_test_name, 0, 0},
    {"test-ycsbk", 0, opt_test_name, 0, 0},
    {"test-rw1fixed", 0, opt_test_name, 0, 0},
    {"threads", 'j', opt_threads, Clp_ValInt, 0},
    {"cores", 0, opt_cores, Clp_ValString, 0},
    {"print", 0, opt_print, 0, Clp_Negate},
    {"epoch-interval", 0, opt_epoch_interval, Clp_ValDouble, 0}};
    